//
//  cmd.h
//  PKFate
//
//  Created by claudis on 15-9-6.
//
//

#pragma once
enum MSGCMD_USER {
	ADD_RESET_PASSWORD_TICKET = 1,
	ADD_RESET_SAFEPWD_TICKET = 2,
	ADD_RIGHTS = 3,
	ADD_ROLE = 4,
	ADD_WITHDRAW_ADDRESS_TICKET = 5,
	ADD_WITHDRAW_TICKET = 6,
	APPEND_RIGHTS = 7,
	AUTH = 8,
	CHANGE_STATUS = 9,
	CHANGE_USERNAME = 10,
	CHECK_NICKNAME = 11,
	EXIST_USER = 12,
	GET_OPERATION_LOG_MODULE_AND_DESC = 13,
	GET_RIGHTS = 14,
	GET_ROLE = 15,
	GET_TICKET = 16,
	GET_USER = 17,
	GET_USER_FROM_TOKEN = 18,
	GET_USER_INFO = 19,
	LIST_RIGHTS = 20,
	LIST_ROLE = 21,
	LIST_ROLE_USERS = 22,
	LOGIN = 23,
	PAGE_LOGIN_LOG = 24,
	PAGE_OPERATION_LOG = 25,
	PAGE_USER = 26,
	REGISTER = 27,
	RESET_PASSWORD = 28,
	RESET_SAFE_PASSWORD = 29,
	ROLE_APPEND_USER = 30,
	ROLE_REMOVE_USER = 31,
	ROLE_UPDATE_RIGHTS = 32,
	SET_AVATAR = 33,
	SET_NICKNAME = 34,
	SET_SAFE_PASSWORD = 35,
	SET_TICKET_TIMEOUT = 36,
	UPDATE_PASSWORD = 37,
	UPDATE_RIGHTS = 38,
	UPDATE_ROLE = 39,
	UPDATE_SAFE_PASSWORD = 40,
	BIND = 55,

	LOOKUP_USER = 50,
	MAKE_FRIEND = 51,
	FETCH_FRIEND = 52,

	SEND_BLIND_MOBILE_TICKET = 53,
	VALID_BIND_MOBILE = 54,
	
};

enum MSGCMD_BILL {
	ADD_CURRENCY_TYPE = 1,
	AGENT_CHANGE_CHILD_COMMISSION = 2,
	AGENT_CHANGE_COMMISSION = 3,
	AGENT_GET_ALL_CHILDS = 4,
	AGENT_INIT_USER = 5,
	AGENT_PAGE_CHILDS = 6,
	AGENT_SET_DEFAULT_CHILD_COMMISSION = 7,
	AGENT_SET_DEFAULT_COMMISSION = 8,
	BATCH_BET = 9,
	BATCH_COMMISSION = 10,
	BATCH_REWARD = 11,
	BATCH_UPDATE_DATE_SUMMARY_TREE = 12,
	BET = 13,
	BET_WITH_FREEZE = 14,
	COMMISSION = 15,
	DEPOSIT = 16,
	FREEZE = 17,
	GET_BALANCE = 18,
	GET_COMMISSION_REPORT = 19,
	GET_COMMISSIONS = 20,
	GET_CURRENCY_TYPE = 21,
	GET_CURRENCY_TYPES = 22,
	GET_DEPOSIT = 23,
	GET_FLOW_SUMMARY = 24,
	GET_FREEZE_LIST = 25,
	GET_LEVEL_CONFIG = 26,
	GET_USER_COMMISSION = 27,
	INIT_BALANCE = 28,
	LIST_BALANCE = 29,
	LIST_DEPOSIT_BY_TXID = 30,
	PAGE_AGENT_BALANCE = 31,
	PAGE_BALANCE = 32,
	PAGE_CURRENCY_TYPES = 33,
	PAGE_DATE_SUMMARY_TREE = 34,
	PAGE_DEPOSIT = 35,
	PAGE_FLOW = 36,
	PAGE_FREEZE = 37,
	REWARD = 38,
	UNFREEZE = 39,
	UPDATE_DATE_SUMMARY_TREE = 40,
	WASHUP_DEPOSIT = 41,

	GET_FORTUNE_DAY_BILLBOARD = 44,
	GET_FORTUNE_WEEK_BILLBOARD = 45,
	GET_FORTUNE_MONTH_BILLBOARD = 46,
	GET_FORTUNE_YEAR_BILLBOARD = 47,
	GET_ALL_GOODS = 53,
	BUY_GOODS = 57,
	GET_BALANCE_STAT = 59,
};

enum MSGCMD_NOTICE {
	PAGE_EMAIL = 10,
	SEND_EMAIL = 9,
	GAME_NOTICE = 2,

	SEND_FRIEND_MESSAGE = 5,
	UPDATE_MESSAGE_STATUS = 6,
	GET_MESSAGE_COUNT = 7,
	PAGE_USER_MESSAGE = 11,

	SEND_FRIEND_INVITE = 12,
	
};

enum MSGCMD_CMS {
	ADD_ARTICLE = 1,
	ADD_CATALOG = 2,
	ADD_TEMPLATE = 3,
	GET_ARTICLE = 4,
	GET_ARTICLES = 5,
	GET_CATALOG = 6,
	GET_CATALOGS = 7,
	GET_TEMPLATE = 8,
	GET_TEMPLATES = 9,
	UPDATE_ARTICLE = 10,
	UPDATE_CATALOG = 11,
	UPDATE_TEMPLATE = 12,
};

enum MSGCMD_GAME {
	GET_USER_GAME_ROUND = 1,
	PAGE_GAME_BET = 2,
	PAGE_GAME_INDEXES = 3,
	PAGE_GAME_INFO = 4,
	PAGE_GAME_ROUND = 5,
	SG_BACCARAT_BEGIN_GAME = 6,
	SG_BACCARAT_BET_GAME = 7,
	SG_BACCARAT_GET_GAME = 8,
	SG_GET_ROOM_TYPES = 9,

	GET_PROFIT_DAY_GAMEBOARD = 10,
	GET_PROFIT_WEEK_GAMEBOARD = 11,
	GET_PROFIT_MONTH_GAMEBOARD = 12,
	GET_PROFIT_YEAR_GAMEBOARD = 13,
	GET_WINRATE_DAY_GAMEBOARD = 14,
	GET_WINRATE_WEEK_GAMEBOARD = 15,
	GET_WINRATE_MONTH_GAMEBOARD = 16,
	GET_WINRATE_YEAR_GAMEBOARD = 17,

	COUNT_GAME_INDEXES = 18,
	GAME_LEVEL_CONFIG = 19,

	GET_GAME_STAT = 20,
	GET_AVALIABLE_GAMES = 21,
	GET_CHANNEL_AVALIABLE_GAMES = 27,
	UPDATE_GAME_STEP = 24,
	GET_GAME_STEP = 25,
	PAGE_GAME_STEP = 26,
};

enum MSGCMD_TASKLIST {
	GET_ROOKIE_TASKLIST = 1,
	DONE_ROOKIE_TASK = 2,
	REWARD_ROOKIE_TASK = 3,
	DONE_INTERVAL_TASK = 4,
	REWARD_INTERVAL_TASK = 5,
	DONE_BANKRUPTCY_TASK = 6,
	REWARD_BANKRUPTCY_TASK = 7,
	DOWN_SIGNIN_TASK = 8,
	REWARD_SIGNIN_TASK = 9,
	GET_SIGNIN_REWARDS = 10,
	GET_DAILY_TASK = 11,
};

enum MSGCMD_TIME {
	SENDTIME = 0,
	RECVTIME = 1,
    SYS_MSG_NOTIFY = 2,
    USER_MSG_NOTIFY = 3,
	REPEAT_LOGIN_NOTIFY = 4,
	BALANCE_UPDATE_NOTIFY = 5,
	FETCH_ONLINE_USERS = 6
};

enum MSGTYPE {
	MSGTYPE_USER = 1,
	MSGTYPE_BILL = 2,
	MSGTYPE_NOTICE = 3,
	MSGTYPE_CMS = 4,
	MSGTYPE_GAME = 5,
	MSGTYPE_TASKLIST = 6,
	MSGTYPE_BJLGAMEMO = 1000,
	MSGTYPE_TIME = 1001,
	MSGTYPE_DZPKGAMEMO = 1002,
	MSGTYPE_SNG_DZPK = 1003,
};